### ISSUE TITLE
Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by thezeroth** [icaruseffect/syncthing-ubuntu-indicator#12]
I'm creating this issue to make the installation process more clear, and to gather info on dependencies so we could update the readme accordingly.
on a clean Ubuntu 14.04 with gnome3 i had to:

sudo apt-get install python-pip python-tz
sudo pip install python-dateutil

to make it work, following packages get installed as a result:
python-colorama python-distlib python-html5lib python-pip python-requests
python-setuptools python-urllib3 python-dateutil

then went here:
https://extensions.gnome.org/extension/615/appindicator-support/
and installed "AppIndicator support"

**Comment by icaruseffect** [comment]
Hi, thank you very much. 
I will put this into the readme and maybe in a setup script.
I think this information is also very useful to build a python virtualenv with it. (see #9)
Sadly development stalled but i will try to go on with it.
